# conda build --output-folder ./conda-out/ ./conda/ -c conda-forge -c cmutel -c diepers

package:
  name: "bw_timex_app"
  version: "0.1.3"

about:
  summary: "Streamlit app for bw_timex"
  home: "https://github.com/TimoDiepers/bw_timex_app"
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: "LICENSE"
  license_url: "https://github.com/TimoDiepers/bw_timex_app/blob/main/LICENSE"
  doc_url: "https://docs.brightway.dev/projects/bw-timex"

requirements:
  build:
    - python={{ python_version }}
    - setuptools
    - wheel
    - pip
  run:
    - python={{ python_version }}
    - bw_timex >=0.2.6
    - bw2io >=0.9.dev38
    - bw2data >=4.0.dev56
    - streamlit >=1.38.0
    - plotly
  entry_points:
    - bw-timex = bw_timex_app.cli:main

source:
  path: ..

build:
  noarch: python
  script:
    - rm -rf $SRC_DIR/docs
    - rm -rf $SRC_DIR/dev
    - {{ PYTHON }} -m pip install . --no-deps -vv
  string: py{{ python_version | replace('.', '') }}
  exclude_files:
    - docs/*
    - dev/*
    - notebooks/*
    - archive/*

files:
  include:
    - bw_timex_app/**
    - ../.streamlit/**