# The regex used is a bit different from original documenation:
# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#loading-data-from-other-files
# Originald documentation implies that the __init__.py only has one line with __version__
{% set version_match = load_file_regex(load_file="bw_timex_app/__init__.py",
regex_pattern='(?:.*)__version__ = "(.+)"') %}
{% set version = version_match[1] %}
# conda build --output-folder ./conda-out/ ./conda/ -c conda-forge -c cmutel -c diepers

package:
  name: "bw_timex_app"
  version: {{ version }}

about:
  summary: "Streamlit app for bw_timex"
  home: "https://github.com/TimoDiepers/bw_timex_app"
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: "LICENSE"
  license_url: "https://github.com/TimoDiepers/bw_timex_app/blob/main/LICENSE"
  doc_url: "https://docs.brightway.dev/projects/bw-timex"

requirements:
  build:
    - python
    - setuptools
  run:
    - python >=3.9
    - bw_timex >=0.2.6
    - bw2io >=0.9.dev38
    - bw2data >=4.0.dev56
    - streamlit >=1.38.0
    - plotly


source:
  path: ..

build:
  noarch: python
  script:
    - rm -rf $SRC_DIR/docs
    - rm -rf $SRC_DIR/dev
    - {{ PYTHON }} -m pip install . --no-deps -vv
  exclude_files:
    - docs/*
    - dev/*
    - notebooks/*
    - archive/*
    
  entry_points:
    - bw-timex = bw_timex_app.cli:main

files:
  include:
    - bw_timex_app/**
    - ../.streamlit/**
